import constants from "../../constants"

export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL'
export const LOG_OUT = 'LOG_OUT'

export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL'
export const SET_GUEST_USER = 'SET_GUEST_USER'

export const CREATE_CHANNEL = 'CREATE_CHANNEL'
export const GET_CHANNEL = 'GET_CHANNEL'
export const GET_CHANNEL_SUCCESS = 'GET_CHANNEL_SUCCESS'
export const GET_CHANNEL_FAIL = 'GET_CHANNEL_FAIL'
export const GET_STREAM_SUCCESS = 'GET_STREAM_SUCCESS'
export const GET_STREAM_FAIL = 'GET_STREAM_FAIL'
export const GET_LIST_CHANNELS_SUCCESS = 'GET_LIST_CHANNELS_SUCCESS'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const OPEN_NOTIFICATION = 'OPEN_NOTIFICATION'
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION'

export const GET_AUTHENTICATED_USER_SUCCESS = 'GET_AUTHENTICATED_USER_SUCCESS'

export const AUCTION_STATUS = constants.AUCTION_STATUS
export const BID = 'BID'
export const BID_RESULT = 'BID_RESULT'

export const SHOW_IMAGE = 'SHOW_IMAGE'

export const OPEN_PAGE = 'OPEN_PAGE'
export const SET_PLAYER_HEIGHT = 'SET_PLAYER_HEIGHT'

export const TOGGLE_CAMERA = 'TOGGLE_CAMERA'
export const TOGGLE_MIKE = 'TOGGLE_MIKE'
export const TOGGLE_LIVE = 'TOGGLE_LIVE'
export const TOGGLE_LIVE_BROADCAST = 'TOGGLE_LIVE_BROADCAST'
export const ADD_VIDEO_DEVICES = 'ADD_VIDEO_DEVICES'
export const ADD_AUDIO_DEVICES = 'ADD_AUDIO_DEVICES'
export const ADD_DEVICE_PERMISSIONS = 'ADD_DEVICE_PERMISSIONS'
export const SET_ACTIVE_VIDEO = 'SET_ACTIVE_VIDEO'
export const SET_ACTIVE_AUDIO = 'SET_ACTIVE_AUDIO'
export const SET_STREAM_LOADING = 'SET_STREAM_LOADING'
export const IS_STOPPING_STREAM = 'IS_STOPPING_STREAM'

export const SET_BROADCAST_KEYS = 'SET_BROADCAST_KEYS'