import constants from "../../constants"

export const GET_CHANNEL = 'GET_CHANNEL'
export const GET_CHANNEL_SUCCESS = 'GET_CHANNEL_SUCCESS'
export const GET_CHANNEL_FAIL = 'GET_CHANNEL_FAIL'
export const GET_STREAM_SUCCESS = 'GET_STREAM_SUCCESS'
export const GET_STREAM_FAIL = 'GET_STREAM_FAIL'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const OPEN_NOTIFICATION = 'OPEN_NOTIFICATION'
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION'

export const AUCTION_STATUS = constants.AUCTION_STATUS
export const BID = 'BID'
export const BID_RESULT = 'BID_RESULT'
export const SET_ADMIN = 'SET_ADMIN'

export const TOGGLE_CAMERA = 'TOGGLE_CAMERA'
export const TOGGLE_MIKE = 'TOGGLE_MIKE'
export const TOGGLE_LIVE = 'TOGGLE_LIVE'
export const ADD_VIDEO_DEVICES = 'ADD_VIDEO_DEVICES'
export const ADD_AUDIO_DEVICES = 'ADD_AUDIO_DEVICES'
export const ADD_DEVICE_PERMISSIONS = 'ADD_DEVICE_PERMISSIONS'
export const SET_ACTIVE_VIDEO = 'SET_ACTIVE_VIDEO'
export const SET_ACTIVE_AUDIO = 'SET_ACTIVE_AUDIO'
export const SET_STREAM_LOADING = 'SET_STREAM_LOADING'

export const SET_BROADCAST_KEYS = 'SET_BROADCAST_KEYS'