export default {
  MODAL_TYPE: {
    LOGIN: 'login',
    SIGNUP: 'signup',
    START_AUCTION: 'startAuction',
    PRODUCT: 'product',
    SETTINGS: 'settings',
    BROADCAST: 'broadcast',
    END_AUCTION: 'endAuction'
  },
  NOTIFICATION_MESSAGES: {
    NO_AUDIO: 'No audio devices found.',
    NO_VIDEO: 'No video devices found.',
    ACCESS_DEVICE_FAILED: 'Failed to access the camera and microphone. To start streaming, you must allow access to both your camera and microphone',
    DEVICE_NOT_FOUND: 'Error: Could not find any available video or audio devices. Please ensure that a camera or microphone is attached to your device, and your privacy settings allow this app access them.',
    CANVAS_FAIL: 'Error: Could not add the selected audio and video devices to the canvas. Please check the app settings to ensure that the correct webcam and microphone are selected.',
    NO_STREAM_KEY: 'No ingest server and streamKey!',
    STREAM_ERROR: 'Error starting stream: Your stream settings are misconfigured. This is likely caused by mismatched channel types. Channel must match the channel type of your Amazon IVS Channel.',
    STREAMING: 'streaming',
    BID_ERROR: 'Unable to place bid',
    BID_SUCCESS: 'Bid submitted',
    AUCTION_CREATED: 'Auction successfully created',
    ACCOUNT_CREATED: 'Account successfully created',
    EMAIL_USED: 'Email already in use',
  },
  NOTIFICATION_TYPES: {
    ERROR: 'error',
    SUCCESS: 'success',
  },
  LOGOUT_ADMIN_ERROR: 'Admin must end auction before logout',
  DEMO_NAME: 'Live Auction',
  SIGN_UP: 'Sign Up',
  SIGN_UP_ALT: 'Sign up',
  LOG_IN: 'Log In',
  LOG_OUT: 'Logout',
  HAVE_AN_ACCOUNT: 'Have an account?',
  CREATE_AN_ACCOUNT: 'Create an account',
  NEW_USER: 'New user?',
  USERNAME: 'Username',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  TOGGLE_PASSWORD_VISIBILITY: 'toggle password visibility',
  LOG_IN_TO_YOUR_ACCOUNT: 'Log in to your account',
  GOT_IT: 'Got It',
  DONE: 'Done',
  IMAGE_LINK_VALIDATION: 'Image link is not valid',
  PASSWORD_REQUIRED: 'Password is required',
  PASSWORD_VALIDATION: 'Password needs at least 1 uppercase, 1 lowercase, 1 number, 1 special character and must be more than 8 letters',
  EMAIL_REQUIRED: 'Email is required',
  EMAIL_INVALID: 'Invalid Email (must have @ mark and include dot after @ mark)',
  USERNAME_REQUIRED: 'Username is required',
  PASSWORD_REGEX: /^(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[0-9])(?=.*?[@$!%*#?&]).{8,}$/,
  /* jQuery email validation */
  EMAIL_REGEX: /^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i,
  STREAM_NOT_AVAILABLE: 'Livestream is not available now',
  STREAM_TURN_ON_DEVICES: `To start streaming, allow access to your camera and microphone`,
  STREAM: 'Stream',
  USERNAME_REGEX: /^.{4,40}$/,
  USERNAME_VALIDATION: 'Value should be more than 4 and less than 40 characters',
  STREAM_OFFLINE: 'Stream Offline',
  STREAM_OFFLINE_SUB: 'Your ingest server url and stream key <br> are found in settings.',
  PRICE_REGEX: /^[0-9]+(\.[0-9]{1,2})?$/i,
  FOUR_TO_FORTY: 'should be more than 4 and less than 40 characters',
  PRODUCT_DESCRIPTION_REGEX: /^.{0,150}$/,
  PRODUCT_DESCRIPTION_VALIDATION: 'Description should be a maximum of 150 characters',
  HIGHEST_BID: 'Highest Bid',
  TIME_LEFT: 'Time Left',
  YOUR_BID: 'Your bid',
  BID_AMOUNT: 'Bid Amount',
  END_AUCTION: 'End Auction',
  CREATE_AUCTION: 'Create Auction',
  AUDIO_SETTINGS: 'Audio/Video Settings',
  BROADCAST_SETTINGS: 'Broadcast Settings',
  STREAM_SETTINGS: 'Stream Settings',
  BID: 'Bid',
  BID_RESULT: {
    HIGHEST: 'HIGHEST BIDDER',
    CANCELLED: 'AUCTION CANCELLED!',
    SOLD: 'ITEM SOLD!',
    NOBID: 'THERE WERE NO BIDS',
    WINNER: `YOU'RE THE WINNER!`,
  },
  START_AUCTION: 'Start Auction',
  ONE_MINUTE: '1 min',
  TWO_MINUTE: '2 min',
  THREE_MINUTE: '3 min',
  FOUR_MINUTE: '4 min',
  FIVE_MINUTE: '5 min',
  VALID_BID: 'Enter a valid bid number',
  BID_REQUIRED: 'Starting bid is required',
  HIGHER_BID: 'Bid must be higher',
  PREVIEW_IMAGE: 'Preview',
  DURATION_REQUIRED: 'Duration is required',
  PREVIEW_IMAGE: 'Image preview',
  PREVIEW_ERROR: 'Image preview error',
  BID_REGEX: /^(0|[1-9]\d*)(\.\d+)?$/,
  BID_REGEX_TWO: /[^0-9.]/g,
  MAX_VALUE: 'Max value is 9,999,999.99',
  AUCTION_STATUS: {
    NOT_STARTED: 'NOT_STARTED',
    STARTED: 'STARTED',
    FINISHED: 'FINISHED'
  },
  AUCTION_UNAVAILABLE: {
    ADMIN: {
      MAIN: 'Get Started!',
      SUB: 'Set up your auction details and start the bidding',
      ICON_NAME: 'admin',
    },
    BIDDER: {
      MAIN: 'Get Ready!',
      SUB: 'When the auction starts you can bid here',
      ICON_NAME: 'bidder',
    },
    LOGGED_OUT: {
      MAIN: 'Get Ready!',
      SUB: 'When the auction starts you can watch the bidding here',
      ICON_NAME: 'logged-out'
    }
  },
  HOLD_SEATS: 'Hold on to your seats!',
  AUCTION_STARTING: 'The auction is about to start',
  PRODUCT: {
    PRODUCT_NAME: {
      label: 'Product Name',
      type: 'productName',
      required: 'Product name is required'
    },
    DESCRIPTION: {
      label: 'Description',
      type: 'description',
      required: 'Description is required'
    },
    STARTING_BID: {
      label: 'Starting Bid',
      type: 'initialBid',
      required: 'Starting bid is required'
    },
    DURATION: {
      label: 'Duration',
      type: 'duration',
      required: 'Duration is required'
    },
    IMAGE_LINK: {
      label: 'Image Link',
      type: 'imageLink'
    },
  },
  STREAM_SETTINGS_SUB: 'Use your Stream Key and Ingest Server URL to start your live stream:',
  STREAM_KEY: 'Stream Key',
  INGEST_SERVER: 'Ingest Server URL',
  COPY: 'Copy',
  PAGE_TYPE: {
    VIDEO: 'video',
    SETTINGS: 'settings'
  },
  MICROPHONE: 'Microphone',
  CAMERA: 'Camera',
  GO_LIVE: 'Go Live',
  LIVE: 'LIVE',
  STOP: 'Stop',
  LAYER_NAME: {
    CAM: 'camera',
    MIC: 'mic',
  },
  CAMERA_OFF: 'Camera Off',
  TOOLTIP: 'Sign up or log in to participate in the auction.',
  TOOLTIPS: {
    AUCTION_START: 'An auction is already in progress',
    MUTE: 'Mute',
    UNMUTE: 'Unmute',
    CAMERA: 'Camera',
    HIDE_CAMERA: 'Hide camera',
    SHOW_CAMERA: 'Show camera',
    SETTINGS: 'Audio/video settings',
    MICROPHONE_UNAVAILABLE: 'Microphone not available',
    CAMERA_UNAVAILABLE: 'Camera not available',
    ALREADY_LIVE: 'Your channel is already live',
  },
  STREAM_RUNNING: 'Your stream is already live with another service',
  ACCOUNT_CREATED: 'Account successfully created',
  MIN_STARTING_AMOUNT: 'Minimum bid must be $ 0.01',
  TWO_DECIMAL: "2 decimal places allowed",
  END_AUCTION_MESSAGE: 'Are you sure you want to end the auction?',
  CANCEL: 'Cancel'
}