import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './state/provider'
import { store } from './state'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers store={store}>
          {children}
          <div id="notification-root"></div>
          <div id="modal-root"></div>
          <div id="confetti-root"></div>
        </Providers>
      </body>
    </html>
  )
}
